image: markhobson/maven-chrome:latest

stages:
  - run-e2e-tests

#----------------------------------------------------
# jobs to run
#----------------------------------------------------
sanityrun-dev:
  stage: run-e2e-tests
  artifacts:
    paths:
      - /target/surefire-reports/*
    when: always
  script:
    - mvn test
  tags:
    - uni