image: markhobson/maven-chrome:latest

stages:
  - run-e2e-tests

#----------------------------------------------------
# jobs to run
#----------------------------------------------------
sanityrun-dev:
  stage: run-e2e-tests
  script:
    - mvn test
  tags:
    - uni